name: e305
description: e6 mobile app
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.0
  intl: ^0.17.0
  mutex: ^3.0.0
  timeago: ^3.1.0
  filesize: ^2.0.1
  expandable: ^5.0.1
  photo_view: ^0.13.0
  sliver_tools: ^0.2.5
  url_launcher: ^6.0.12
  path_provider: ^2.0.5
  dio_http_cache: ^0.3.0
  carousel_slider: ^4.0.0
  pull_to_refresh: ^2.0.0
  cupertino_icons: ^1.0.3
  package_info_plus: ^1.3.0
  loading_indicator: ^3.0.2
  permission_handler: 8.1.1 # ^8.2.2 is broken
  shared_preferences: ^2.0.8
  image_gallery_saver: ^1.7.0
  cached_network_image: ^3.0.0
  font_awesome_flutter: ^9.1.0
  flutter_cache_manager: ^3.1.2
  persistent_bottom_nav_bar: ^4.0.2
  flutter_staggered_grid_view: ^0.4.1

  infinite_scroll_pagination:
    git:
      url: git://github.com/EdsonBueno/infinite_scroll_pagination
      ref: develop

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.7
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/e6.png
    - assets/icon.png

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  image: assets/icon.png
  color: "000000"


