name: Build on Push

on: push

jobs:
  ios-build:
    runs-on: macos-latest
    steps:
    - name: setup actions
      uses: actions/checkout@v3

    - name: setup flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable' 

    - name: configure release version
      run: |
        echo "GITHUB_BRANCH=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
        echo "GITHUB_SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: get dependencies
      run: flutter pub get

    - name: build release
      run: flutter build ios --no-codesign --dart-define=branch=$GITHUB_BRANCH --dart-define=commit=$GITHUB_SHA_SHORT

    - name: package release
      run: |
        cd build/ios/iphoneos
        mkdir Payload
        mv Runner.app Payload/Runner.app
        zip -9 -r e305.zip Payload
        mv e305.zip ../../../e305.ipa

    - name: upload release
      uses: actions/upload-artifact@v3
      with:
        name: release-ios
        path: e305.ipa

  android-build:
    runs-on: ubuntu-latest
    steps:

    - name: setup actions
      uses: actions/checkout@v3

    - name: setup java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '12'

    - name: setup flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable' 

    - name: configure release keys
      env:
        KEYSTORE: ${{ secrets.KEYSTORE }}
        KEYCONFIG: ${{ secrets.KEYCONFIG }}
      run: | 
        mkdir -p android/app/keys
        echo "$KEYSTORE" | base64 -d > android/app/keys/key.pkcs
        echo "$KEYCONFIG" | base64 -d > android/app/keys/key.properties

    - name: configure release version
      run: |
        echo "GITHUB_BRANCH=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
        echo "GITHUB_SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: get dependencies
      run: flutter pub get

    - name: build release
      run: flutter build apk --dart-define=branch=$GITHUB_BRANCH --dart-define=commit=$GITHUB_SHA_SHORT

    - name: upload release
      uses: actions/upload-artifact@v3
      with:
        name: release-apk
        path: build/app/outputs/apk/release/app-release.apk
